# Generated by Django 4.2.6 on 2024-09-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='locality',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
